project:
  type: manuscript
  render: 
    - article.qmd
manuscript:
  meca: true
  manuscript-url: https://notebooks-now.github.io/submission-quarto-full/
format:
  html:
    toc: true
    format-links: [agu-pdf, docx]
    comments: 
      hypothesis: true   
  agu-pdf: default
  docx: default
  jats: default
notebook-view: 
  - notebook: notebooks/data-screening.ipynb  
    title: Data Screening
