project:
  type: manuscript

manuscript:
  article: article.qmd
  resources:
    - data/catalogoComunSV_1663233588717.csv
    - data/lapalma_ign.csv
  code-links: [repo, devcontainer, binder]


format:
  html:
    theme: cosmo
    comments: 
      hypothesis: true
    citations-hover: true
    crossrefs-hover: true
    toc-location: left
    title-block-style: manuscript
  agu-pdf: 
    notebook-links: inline
  docx: default
  jats: default

citation:
  container-title: Earth and Space Science
  type: article-journal
  issued: 2023-05-01
  doi: "10.1136/bmj.m4290"

