project:
  type: manuscript
  render: 
    - article.qmd

manuscript:
  meca: true

format:
  html:
    toc: true
    format-links: [agu-pdf, docx]
    comments: 
      hypothesis: true    
  agu-pdf: default
  docx: default
  jats: default