#!/bin/bash -v

RELEASE_JSON=$(curl https://quarto.org/docs/download/_prerelease.json)
VERSION=$(jq -r  '.version' <<< "${RELEASE_JSON}") 

echo
echo Installing Quarto $VERSION...
echo

curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v$VERSION/quarto-$VERSION-linux-amd64.deb
dpkg -x quarto-$VERSION-linux-amd64.deb .quarto
rm -rf quarto-$VERSION-linux-amd64.deb

mkdir -p ./.local/bin
ln -s ~/.quarto/opt/quarto/bin/quarto ~/.local/bin/quarto

echo
echo Installed Quarto $VERSION...
echo

echo Installing TinyTex...
echo

quarto install tinytex --no-prompt

echo
echo Installed TinyTex...
echo

echo Configuring VSCode...
echo

# Download and install VS Code server
CODE_VERSION=4.16.1

wget -q -O code-server.tar.gz https://github.com/coder/code-server/releases/download/v$CODE_VERSION/code-server-$CODE_VERSION-linux-amd64.tar.gz
tar xzf code-server.tar.gz

mv "code-server-$CODE_VERSION-linux-amd64" .code-server

mkdir -p ./.local/bin
ls -la ~/.code-server/bin/

ln -s ~/.code-server/bin/code-server ~/.local/bin/code-server  

rm -rf code-server.tar.gz

code-server --install-extension ms-python.python
code-server --install-extension sumneko.lua
code-server --install-extension quarto.quarto

echo
echo Configured VSCode...
echo

# Enable the proxy extension in notebook and lab
python3 -m pip install jupyter-server-proxy
